# Generated by Django 3.2.12 on 2022-03-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220329_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sueprhost',
            new_name='superhost',
        ),
    ]
