# Generated by Django 3.2.12 on 2022-04-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20220426_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomtype'),
        ),
    ]
